name: Verify code building

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:12.14.1-alpine

    steps:
      - uses: actions/checkout@v1
      - name: Install & Build
        run: |
          npm install
          npm run build
